### ISSUE TITLE
Still functioning?

### ISSUE THREAD

**Issue by VarLad** [gstavrinos/ROS.jl_deprecated#1]
No updates... Is this package dead?

**Comment by gstavrinos** [comment]
This package was never a functional ROS C++ wrapper. It was made public as a reference point for people that are interested in wrapping C++ ROS for Julia. I am very interested in it, but I currently do not have the time to work on it. You are free to experiment and make PRs :)

**Comment by gstavrinos** [comment]
@clad26 Update: This repo is being archived in favor of my new ROS.jl repository. Check that out if you are still interested.
